[workspace]
authors = ["Agustin Corbat <acorbat@df.uba.ar>"]
channels = ["conda-forge"]
name = "workshop_3d_dl_segmentation"
platforms = ["win-64", "linux-64", "osx-arm64"]

[system-requirements]
cuda = "12.0"

[dependencies]
python = "3.11.*"
napari = ">=0.6.6,<0.7"
cellpose = "*"
stardist = "*"
bioio = "*"
jupyterlab = ">=4.5.1,<5"

[target.win.dependencies]
pytorch-gpu = ">=2.9.1,<3"

[target.linux.dependencies]
pytorch-gpu = ">=2.9.1,<3"

[tasks]
download-data = "curl -L https://zenodo.org/records/17986091/files/Lund.tif --output data/Lund.tif --create-dirs && curl -L https://git.mpi-cbg.de/rhaase/clij2_example_data/-/raw/master/lund1051_resampled.tif --output data/lund1051_resampled.tif --create-dirs"
cellpose = "jupyter lab notebooks/cellpose_napari_3d.ipynb"
stardist = "jupyter lab notebooks/stardist_napari_3d.ipynb"

[pypi-dependencies]
bioio-tifffile = ">=1.3.0, <2"
tensorflow = ">=2.13,<3"
